spring:
  application:
    name: shiply-gateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**
          filters: []

server:
  port: 8087
